.\" man page for s3fuse
.TH S3FUSE_SHA256_SUM 1 2013-01-26 "s3fuse 0.13" "s3fuse_sha256_sum"

.SH NAME
\fBs3fuse_sha256_sum\fR - Generate SHA256 sums

.SH SYNOPSIS
.B  s3fuse_sha256_sum
.I  file

.SH DESCRIPTION
\fBs3fuse_sha256_sum\fR generates SHA256 sums of files using the same
hash-of-hash-lists method that \fBs3fuse\fR(1) uses when uploading and 
downloading files. These sums can be compared against those reported by
\fBs3fuse\fR(1) in the \fBs3fuse_sha256\fR extended attribute.

.SH AUTHORS
Tarick Bedeir <tarick@bedeir.com>

.SH SEE ALSO
\fBs3fuse\fR(1)
